export default {
  COLORS: {
    WHITE: "#FFF",
    BLACK: "#000",
    BLACKTOGGLE: "#000",
    PURPLE_DARK: "#820ad1",
    PURPLE_MID: "#5f259f",
    PURPLE_LIGHT: "#5f259f",
    GRAY_700: "#1B1D1E",
    GRAY_600: "#333638",
    GRAY_500: "#5C6265",
    GRAY_400: "#B9BBBC",
    GRAY_300: "#DDDEDF",
    GRAY_200: "#EFF0F0",
    GRAY_100: "#FAFAFA",
    GRAY_DEFAULT: "#efefef",
  },
  FONT_FAMILY: {
    ROBOTO: {
      REGULAR: "Roboto_400Regular",
      MEDIUM: "Roboto_500Medium",
      BOLD: "Roboto_700Bold",
    },
    GRAPHIK: {
      LIGHT: "GraphikLight",
      REGULAR: "GraphikRegular",
      MEDIUM: "GraphikMedium",
      SEMIBOLD: "GraphikSemibold",
      BOLD: "GraphikBold",
      BLACK: "GraphikBlack",
      SUPER: "GraphikSuper",
    },
  },
  FONT_SIZE: {
    XS: 12,
    SM: 14,
    MD: 16,
    LG: 18,
    XL: 24,
    XXL: 32,
  },
};
